#!/bin/bash

# Verificar si se pasó al menos el segundo parámetro opcional
if [ "$#" -lt 1 ]; then
    echo "Uso: $0 <optional_second_param>"
    exit 1
fi

# Parámetro opcional
second_param=$1

# Ruta del workspace
workspace_path="$PWD"
workspace_basename=$(basename "$workspace_path")
FILE=$workspace_basename
BIN=./bin/$FILE
config_file="./$FILE.config"

# Compilar
make $BIN

# Verificar si el binario fue creado y ejecutar
if test -f $BIN; then
    if [ -n "$second_param" ]; then
        $BIN "$config_file" "$second_param"
    else
        $BIN "$config_file"
    fi
fi
