#!/bin/bash
workspace_path="$PWD"
workspace_basename=$(basename "$workspace_path")
FILE=$workspace_basename
BIN=./bin/$FILE
make $BIN
if test -f $BIN; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 -s $BIN ./$FILE.config
fi